name: update_example
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
